version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: 396gidb-frontend
    tty: true
    volumes:
      - ./frontend:/app/frontend
    command: sh -c "cd /app/frontend/react-app && yarn start"
    ports:
      - 3000:3000
  api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: 396gi-backend
    volumes:
      - ./backend:/app/backend
    command: reflex -r '\.go$$' -s -- sh -c 'go run /app/backend/go-app/main.go -port=8000'
    ports:
      - 8000:8000
    tty: true
  mysql:
    image: mysql:8.0.16
    container_name: 396gi-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 396gi-db
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    links:
      - go
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    ports:
      - 1234:80
    volumes:
      - /sessions
